# Generated by Django 3.1.7 on 2021-04-17 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(default='user', max_length=40),
            preserve_default=False,
        ),
    ]
