# Generated by Django 3.1.7 on 2021-04-18 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_organization_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='photo',
            new_name='media',
        ),
    ]
